# Generated by Django 2.2.6 on 2019-10-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmetadata',
            name='phone_number',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
