# Generated by Django 2.2.6 on 2019-10-11 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qr_code.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_code', '0002_linksmetadata_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrcodeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=qr_code.models.productFile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
