# Generated by Django 2.2.6 on 2019-10-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0008_auto_20191011_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmetadata',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='phone_number',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='pinterest_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='portfolio_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='resume_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linksmetadata',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
    ]
