# Generated by Django 2.2.6 on 2019-10-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0009_auto_20191015_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmetadata',
            name='phone_number',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
