# Generated by Django 2.2.6 on 2019-10-21 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_code', '0010_auto_20191015_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdatedTime', models.DateTimeField(auto_now_add=True)),
                ('other_user', models.TextField(max_length=200, null=True)),
                ('interaction_notes', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactionnotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
