# Generated by Django 2.2.6 on 2019-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0013_linksdatabasechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeimage',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=''),
        ),
    ]
