# Generated by Django 2.2.6 on 2019-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0014_auto_20191105_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmetadata',
            name='email_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondarylinksmetadata',
            name='email_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
